.TH mce_listen ""
.\" Copyright (c) 2007 Tim Hockin (thockin@google.com)
.SH NAME
mce_listen \- MCE event listener
.SH SYNOPSIS
\fBmce_listen\fP [\fIoptions\fP]

.SH DESCRIPTION
\fBmced\fP is the sysem-wide MCE event catcher.  \fBmce_listen\fP is a
simple shell-friendly tool which connects to \fBmced\fP and listens for
events.  When an event occurs, \fBmce_listen\fP will print it on stdout.

.SH OPTIONS
.TP
.BI \-c "\fR, \fP" \--count " events"
Receive up to a maximum number of MCE events, then exit.  Specifying 0
events here will cause \fBmce_listen\fP to open the connection and
immediately exit.  This is useful as a 'ping' of sorts.
.TP
.BI \-s "\fR, \fP" \--socketfile " filename"
This option changes the name of the UNIX domain socket which
\fBmce_listen\fP opens.  Default is \fI/var/run/mced.socket\fP.
.TP
.BI \-t "\fR, \fP" \--time " seconds"
Listen for the specified time in seconds, before exiting.  Setting this to
0 or less will cause \fBmce_listen\fP to listen with no timeout.  Default
is no timeout.
.TP
.BI \--dbus
Listen for events on D-Bus rather than the UNIX socket.  Default is to use
the UNIX socket.
.TP
.BI \--dbus-session-bus
Listen for D-Bus signals on the session bus, rather than the system bus.
Default is the system bus.
.TP
.BI \-v "\fR, \fP" \--version
Print version information and exit.
.TP
.BI \-h "\fR, \fP" \--help
Show help and exit.

.SH FILES
.PD 0
.B /var/run/mced.socket
.PD

.SH BUGS
There are no known bugs.  To file bug reports, see \fBAUTHORS\fP below.
.SH SEE ALSO
regcomp(3), sh(1), socket(2), connect(2)
.SH AUTHORS
Tim Hockin <thockin@hockin.org>
.br

